In [1]:
import numpy as np
import matplotlib.pyplot as plt
import gmsh
import meshio

In [2]:
class Element:
    def __init__(self, ):
        pass

In [3]:
gmsh.initialize()

gmsh.model.add("rectangle")

lc = 0.2
p1 = gmsh.model.geo.addPoint(0, 0, 0, lc)
p2 = gmsh.model.geo.addPoint(2.0, 0, 0, lc)
p3 = gmsh.model.geo.addPoint(2.0, 1.0, 0, lc)
p4 = gmsh.model.geo.addPoint(0.0, 1.0, 0, lc)

l1 = gmsh.model.geo.addLine(p1, p2)
l2 = gmsh.model.geo.addLine(p2, p3)
l3 = gmsh.model.geo.addLine(p3, p4)
l4 = gmsh.model.geo.addLine(p4, p1)

cl = []
cl.append(gmsh.model.geo.addCurveLoop([l1, l2, l3, l4]))

srf = gmsh.model.geo.addPlaneSurface(cl)

gmsh.model.geo.synchronize()

gmsh.model.addPhysicalGroup(1, [l1, l2, l3], name="boundary_one")
gmsh.model.addPhysicalGroup(1, [l4], name="boundary_two")
gmsh.model.addPhysicalGroup(2, [srf], name="surface")

gmsh.model.mesh.generate(2)

gmsh.fltk.run()

gmsh.option.setNumber("Mesh.Binary", 1)
gmsh.write("rectangle.msh")
gmsh.finalize()

Info    : Meshing 1D...
Info    : [  0%] Meshing curve 1 (Line)
Info    : [ 30%] Meshing curve 2 (Line)
Info    : [ 60%] Meshing curve 3 (Line)
Info    : [ 80%] Meshing curve 4 (Line)
Info    : Done meshing 1D (Wall 0.00029881s, CPU 0.00177s)
Info    : Meshing 2D...
Info    : Meshing surface 1 (Plane, Frontal-Delaunay)
Info    : Done meshing 2D (Wall 0.00374977s, CPU 0.004215s)
Info    : 80 nodes 162 elements
-------------------------------------------------------
Version       : 4.15.1
License       : GNU General Public License
Build OS      : Linux64-sdk
Build date    : 20260216
Build host    : gmsh.info
Build options : 64Bit ALGLIB[contrib] ANN[contrib] Bamg Blas[petsc] Blossom Cgns DIntegration Dlopen DomHex Eigen[contrib] Fltk Gmm[contrib] Hxt Jpeg Kbipack Lapack[petsc] LinuxJoystick MathEx[contrib] Med Mesh Metis[contrib] Mmg Mpeg Netgen Nii2mesh ONELAB ONELABMetamodel OpenCASCADE OpenCASCADE-CAF OpenGL OpenMP OptHom PETSc Parser Plugins Png Post QuadMeshingTools QuadTri Solver T

In [4]:
mesh = meshio.read("rectangle.msh")

first_triangle_coords = mesh.cells_dict['triangle'][0]
mesh.cell_sets_dict

{'boundary_one': {'line': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18, 19, 20, 21, 22, 23, 24], dtype=uint64)},
 'boundary_two': {'line': array([25, 26, 27, 28, 29], dtype=uint64)},
 'surface': {'triangle': array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
          13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
          26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
          39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
          52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
          65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
          78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
          91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
         104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
         117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127],
        dtype=uin

In [5]:
print(mesh.points.shape)                 # число узлов
print(mesh.cells_dict["line"].shape)     # число граничных line-элементов
print(mesh.cells_dict["triangle"].shape) # число треугольников

print(mesh.cell_sets_dict["boundary_one"]["line"])
print(mesh.cell_sets_dict["boundary_two"]["line"])

(80, 3)
(30, 2)
(128, 3)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[25 26 27 28 29]


In [6]:
print(mesh.cells_dict["line"])
print(mesh.cells_dict["triangle"])

[[ 0  4]
 [ 4  5]
 [ 5  6]
 [ 6  7]
 [ 7  8]
 [ 8  9]
 [ 9 10]
 [10 11]
 [11 12]
 [12  1]
 [ 1 13]
 [13 14]
 [14 15]
 [15 16]
 [16  2]
 [ 2 17]
 [17 18]
 [18 19]
 [19 20]
 [20 21]
 [21 22]
 [22 23]
 [23 24]
 [24 25]
 [25  3]
 [ 3 26]
 [26 27]
 [27 28]
 [28 29]
 [29  0]]
[[48 49 62]
 [52 55 61]
 [34 67 68]
 [67 44 68]
 [56 60 63]
 [59 38 64]
 [48 62 78]
 [52 61 79]
 [63 60 77]
 [64 38 76]
 [30 66 69]
 [65  7 70]
 [24 25 49]
 [35 24 49]
 [48 35 49]
 [43 40 46]
 [46 35 48]
 [40 39 46]
 [21 22 31]
 [31 39 40]
 [43 46 47]
 [20 21 57]
 [31 22 39]
 [23 35 39]
 [11 12 55]
 [39 35 46]
 [ 8  9 34]
 [50 33 51]
 [31 40 41]
 [22 23 39]
 [30 20 57]
 [51 52 53]
 [21 31 57]
 [10 33 50]
 [34  9 50]
 [51 53 54]
 [10 11 33]
 [42 43 45]
 [51 33 52]
 [23 24 35]
 [ 9 10 50]
 [17 18 38]
 [33 11 55]
 [14 15 37]
 [41 42 44]
 [47 46 48]
 [27 28 36]
 [28 29 56]
 [41 40 42]
 [42 40 43]
 [52 33 55]
 [ 5  6 32]
 [19 20 30]
 [38 18 58]
 [18 19 58]
 [31 41 57]
 [19 30 58]
 [36 28 56]
 [15 16 59]
 [ 4  5 60]
 [13 14 6

In [7]:
mesh.cells_dict["triangle"]

array([[48, 49, 62],
       [52, 55, 61],
       [34, 67, 68],
       [67, 44, 68],
       [56, 60, 63],
       [59, 38, 64],
       [48, 62, 78],
       [52, 61, 79],
       [63, 60, 77],
       [64, 38, 76],
       [30, 66, 69],
       [65,  7, 70],
       [24, 25, 49],
       [35, 24, 49],
       [48, 35, 49],
       [43, 40, 46],
       [46, 35, 48],
       [40, 39, 46],
       [21, 22, 31],
       [31, 39, 40],
       [43, 46, 47],
       [20, 21, 57],
       [31, 22, 39],
       [23, 35, 39],
       [11, 12, 55],
       [39, 35, 46],
       [ 8,  9, 34],
       [50, 33, 51],
       [31, 40, 41],
       [22, 23, 39],
       [30, 20, 57],
       [51, 52, 53],
       [21, 31, 57],
       [10, 33, 50],
       [34,  9, 50],
       [51, 53, 54],
       [10, 11, 33],
       [42, 43, 45],
       [51, 33, 52],
       [23, 24, 35],
       [ 9, 10, 50],
       [17, 18, 38],
       [33, 11, 55],
       [14, 15, 37],
       [41, 42, 44],
       [47, 46, 48],
       [27, 28, 36],
       [28, 2